Fix error when no title is defined for legend
If no title was defined in `legend.area.title`, a JS error `Line 907: TypeError: title.getBBox is not a function` was thrown.

Here is a fix where we test the existence of the title before using its size.